#!/bin/sh

set -eu

if ! emerge -p "${@}"
then
	emerge --autounmask-write "${@}" || :

	find '/etc/portage' -name '._cfg*' | while read l
	do
		dirname="$(dirname "${l}")"
		filename="$(basename "${l}" | cut -d _ -f 3-)"

		mv "${l}" "${dirname}/${filename}"
	done
fi

emerge "${@}"
